In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

This is an implementation of Neural Networks from scratch. This is P1 Intro and Neuron Code

# P1 Basic Idea behind the inputs, weights and biases of a neural network

In [2]:
inputs = [1.2, 3.4, 4.6]
weights = [2.2, 4.5, 5.2]
bias = 4

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

45.86


# P2 Coding a Layer

In [3]:
inputs = [1,2,3]
weights = [0.2,0.8,-0.5]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

2.3


Adding another input neuron and weights, we are trying to see the layer the leads to the value of an ouput neuron

In [4]:
inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + bias
print(output)

4.8


Building a layer of 4 input and 3 output

In [5]:
inputs = [1,2,3,2.5]

weights1 = [0.2,0.8,-0.5,1.0]
weights2 = [0.5,-0.91,0.26,-0.5]
weights3 = [-0.26,-0.27,0.17,0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
         inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]

print(output)

[4.8, 1.21, 2.385]


# P3 The Dot Product

simplified process of nerual nets calculation. Going from previously used hard math to following for loop. 

In [6]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

layer_outputs = []
for neuron_weights, neuron_biases in zip(weights,biases):
    neuron_output = 0
    for n_input, weights in zip(inputs,neuron_weights):
        neuron_output += n_input*weights
    neuron_output += neuron_biases
    layer_outputs.append(neuron_output)
    
print(layer_outputs)

[4.8, 1.21, 2.385]


dot product

In [7]:
import numpy as np

inputs = [1,2,3,2.5]
weights = [0.2,0.8,-0.5,1.0]
bias = 2

output = np.dot(weights, inputs) + bias
print(output)

4.8


dot product of a layer of neuron

In [8]:
inputs = [1,2,3,2.5]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

output = np.dot(weights,inputs) + biases
print(output)

[4.8   1.21  2.385]


# P4 Batches, Layers and Objects

In [9]:
 inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

output = np.dot(inputs,np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


adding another layer

In [10]:
inputs = [[1,2,3,2.5],
          [2.0,5.0,-1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

biases = [2,3,0.5]

weights2 = [[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,-0.13]]

biases2 = [-1,2,-0.5]

layer1_outputs = np.dot(inputs,np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs,np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


Converting neural networks to object layers

In [11]:
import numpy as np

np.random.seed(0)

X = [[1,2,3,2.5],
     [2.0,5.0,-1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1,n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs , self.weights) + self.biases

        
layer1 = Layer_Dense(4,5)
layer2 = Layer_Dense(5,2)

layer1.forward(X)
# print(layer1.output)
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]
